name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:dd-MM-yyyy)$(Rev:.r)

trigger: none

variables:
  location: westeurope
  resourceGroupName: RG2
  dataFactoryName: adffdlm2

pool:
  vmImage: windows-latest

stages:
  - stage: DEPLOYINFRA
    jobs:
      - job:
        steps:
          - task: AzurePowerShell@5
            displayName: Deployer RG $(resourceGroupName)
            inputs:
              azureSubscription: "DemoADFSC"
              azurePowerShellVersion: LatestVersion
              ScriptType: "InlineScript"
              Inline: |
                write-host "##[warning]Déployer RG: " ${{ variables.resourceGroupName }} 
                New-AzResourceGroup -Name ${{ variables.resourceGroupName }}  -Location ${{variables.location}} -Force

          - task: AzurePowerShell@5
            displayName: Deployer ADF $(dataFactoryName)
            inputs:
              azureSubscription: "DemoADFSC"
              azurePowerShellVersion: LatestVersion
              ScriptType: "FilePath"
              scriptPath: DeployADF.ps1
